andniven_sdo.py - added informal constants to clarify parse function'…
Boneill3/CANopen-monitor pull request #10
Opened 2021-03-06 08:10 UTC by TheDragonMask

…s conditional message processing

2021-03-06 17:56 UTC, Boneill3 reviewed
I was a little confused by max_plus_1 when I first saw it, though it is actually a perfect description. I think this could be simplified using a range like SDO_TX_RANGE = range(0x580, 0x600)

Also, we I think these constants could be moved to the utilities.py

2021-03-06 18:00 UTC, Boneill3 commented
Correction, check out the message type in can/message.py it actually already contains all of the ranges already so we should be able to just leverage that here!

2021-03-06 18:10 UTC, Boneill3 requested changes
Just testing using the request changes option, my comments are already above.

2021-03-06 20:48 UTC, thaotran9 commented on canopen_monitor/parse/sdo.py
> +
these ranges are in message.py, I think we can reuse them instead of creating new fields for this class.

2021-03-08 23:56 UTC, TheDragonMask commented on canopen_monitor/parse/sdo.py
> +
Good point, I will try to figure out how to import then from messages.py after our meeting with Casamento then.

2021-03-12 08:52 UTC, TheDragonMask commented
Came across a weird error when trying to "amend" my previous commit, and since then github doesn't like this pull-request. I've also made a mess of things by trying to revert the commit several times, and at this point it is simpler for me to just make another one pull-request that makes the same changes. In the interest of keeping this one as a record, I am closing it with this comment

2021-03-12 08:52 UTC, closed without merging