add some new comments
Boneill3/CANopen-monitor pull request #12
Opened 2021-03-07 18:43 UTC by Sanlinlin

update and add some new comments for some functions

2021-03-08 22:26 UTC, J8cob1 requested changes
There are a couple of small things we may want to address, but overall, I like the changes

2021-03-08 22:26 UTC, J8cob1 commented on canopen_monitor/ui/message_pane.py
> +        Initialize the x position to be zero.
Knit pick: you could say "Initialize the x and y positions to 0"

It's still fine though

2021-03-08 22:26 UTC, J8cob1 commented on canopen_monitor/ui/pane.py
> +        Limit the scroll on the y axis
This comment seems like it might be off a little bit. Maybe it's better as "Get the y scroll limit"

You'd have to check with someone who knows this code a little better to be sure

2021-03-08 22:26 UTC, J8cob1 commented on canopen_monitor/ui/pane.py
> +        Limit the scroll on the x axis
Same idea as with the y scroll_limit function

2021-03-08 22:29 UTC, Sanlinlin commented on canopen_monitor/ui/pane.py
> +        Limit the scroll on the x axis
Yeah, I agree with that. Thank you your review

2021-03-08 23:54 UTC, TheDragonMask approved these changes
This looks good to me!

2021-03-09 00:18 UTC, obi1kanogli commented on canopen_monitor/ui/pane.py
> +        """
Definitely nice to add the comments in here.

2021-03-10 04:09 UTC, merged