Parse init and can open
Boneill3/CANopen-monitor pull request #2
Opened 2021-02-25 22:26 UTC by J8cob1

Initial PR

2021-03-06 02:07 UTC, J8cob1 commented
Ready for review at any time

2021-03-06 18:36 UTC, Boneill3 requested changes
I updated the EDS test spec so that it runs now. If you run those tests, you will find some are failing. I think this is from changing the camel to snake. There is also something in there that is getting handling attributes in the EDS file. Like parameter name. 

Maybe you can refactor camel_to_snake to make it more clear what is actually camel_to_snake and what is parsing the attribute.

2021-03-07 00:48 UTC, J8cob1 commented
I fixed the function

2021-03-07 01:25 UTC, Boneill3 requested changes
I like all the additional comments on camel to snake! There's a lot happening there. 

Do you think camel_to_snake still makes sense for a name for it?

The only change I'm suggesting here is that we don't need to keep the old version in the comments.

2021-03-07 01:25 UTC, Boneill3 commented on canopen_monitor/parse/eds.py
> +    return new_name"""
I don't think we need to keep this as a comment. If there are weird edge cases, I think we should document it with unit tests and we can always pull this up from git if needed. Let me know if you think otherwise!

2021-03-07 19:43 UTC, J8cob1 commented on canopen_monitor/parse/eds.py
> +    return new_name"""
Oh. I probably forgot to take that out. Thank you for pointing that out

2021-03-09 00:23 UTC, J8cob1 commented on canopen_monitor/parse/eds.py
> +    return new_name"""
"Do you think camel_to_snake still makes sense for a name for it?"

No. I think it's fine

2021-03-10 02:30 UTC, merged