Broneill app.py
Boneill3/CANopen-monitor pull request #4
Opened 2021-02-26 05:29 UTC by Boneill3

This pull requests fixes a bug where control+down and control+up was not working when using ubuntu. 

Additionally, some minor cleanup was done in app.py including:
- Making keyboard input values reference the same location for documentation and actually testing input
- Adding comments for every function
- Converting magic numbers to constants

2021-02-26 05:39 UTC, Boneill3 commented on canopen_monitor/app.py
>              self.hotkeys_win.toggle()
I think this whole if/else block could be replaced by a dictionary where the key is the input and the value is the function (or includes the function). I think this would be worth it if it ties in to the KeyMap above. Meaning changes to keys or key mapping would all occur in about the same place. Also, could be overkill.

2021-02-26 20:31 UTC, Boneill3 commented on canopen_monitor/app.py
> +    :param value: number of spaces to pad hex value
Add type to documentation

2021-03-07 05:31 UTC, nhanlt81 commented on canopen_monitor/app.py
>              self.hotkeys_win.toggle()
I am thinking that it may be overskill here. Instead, add the comments to clear what KeyMap.F1.value[2] is meant.  It may be simple and efficient.

2021-03-07 05:34 UTC, nhanlt81 commented on canopen_monitor/app.py
>              self.hotkeys_win.toggle()
Overall, it has been really good. I like the Keymap class. It is really easy to understand.

2021-03-08 01:16 UTC, nhanlt81 commented on canopen_monitor/app.py
> +        elif (input == KeyMap.LEFT_ARR.value[2]):
Add the comments here to clarify what value[2] is. It may be simpler than changing KeyMap to dictionary.

2021-03-09 00:28 UTC, TheDragonMask commented on canopen_monitor/app.py
> +KEY_S_DOWN = 337
A typo? If we ever have 3 panes again, this might be good to change to have an actual difference between up and down.

2021-03-09 00:30 UTC, Boneill3 commented on canopen_monitor/app.py
> +KEY_S_DOWN = 337
Shift down should be 336, not 337. oops!

2021-03-12 10:11 UTC, TheDragonMask requested changes
Can you edit line 13 to reflect the real Key_S_Down value? Thanks.

2021-03-12 10:11 UTC, TheDragonMask commented on canopen_monitor/app.py
> +KEY_S_DOWN = 337
Probably best to change this before we rebase and merge this with the master branch.

2021-03-15 00:46 UTC, Boneill3 commented on canopen_monitor/app.py
> +KEY_S_DOWN = 337
This should be fixed now.

2021-03-16 00:28 UTC, merged